package nz.co.cpc.bridgeauctionrecorder;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.webkit.JavascriptInterface;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
 private static final int REQ_SAVE_FILE=1001,REQ_OPEN_JSON=1002; private WebView webView; private String pendingFileName,pendingMimeType,pendingContent;
 @Override protected void onCreate(Bundle b){super.onCreate(b);webView=new WebView(this);webView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE);setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setBuiltInZoomControls(false);s.setDisplayZoomControls(false);webView.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){super.onPageFinished(v,u);installCompactUi();}});webView.setWebChromeClient(new WebChromeClient());webView.addJavascriptInterface(new AndroidFiles(),"AndroidFiles");webView.loadUrl("file:///android_asset/www/index.html");}
 private void installCompactUi(){String js="(function(){"+
 "const st=document.createElement('style');st.textContent=`header{padding:7px 10px}h1{font-size:18px;margin:0 0 1px}.meta{font-size:11px}main{padding:4px 6px 12px}.card{padding:6px;margin-bottom:4px;border-radius:9px}.grid{gap:5px}.section-title{margin-bottom:2px}.auction .seat,.auction .bid{padding:4px}.bid{min-height:31px}.last{outline:2px solid #a7bfd2}.bidgrid{display:block!important;margin-top:4px!important}.callrow{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin-bottom:4px}.contractgrid{display:grid;grid-template-columns:repeat(5,1fr);gap:3px}.bidgrid button{min-height:43px!important;padding:4px 2px!important;font-size:18px;border-radius:7px}.callrow button{font-size:17px;color:#fff}.callrow .pass{background:#299447;border-color:#237f3d}.callrow .double{background:#2878c7;border-color:#2169af}.callrow .redouble{background:#cf3434;border-color:#b82d2d}.contractgrid .clubs,.contractgrid .spades{color:#111}.contractgrid .diamonds,.contractgrid .hearts{color:#d32626}.contractgrid .notrump{color:#17324d}.bidgrid button:disabled{background:#d9dde0!important;color:#92989d!important;border-color:#c8cdd1!important;opacity:1}.tools{margin-top:4px}.liveControls{grid-template-columns:1fr 1fr!important}.liveControls label:first-child{display:none}.liveControls label:nth-child(4){display:none}.finalBidRow{display:none!important}#alertBtn,#alertBox{display:none!important}`;document.head.appendChild(st);"+
 "const top=document.querySelector('main .card .grid');if(top)top.classList.add('liveControls');"+
 "window.legalBid=function(b){const d=data(),bs=d.bids,di=seats.indexOf(d.dealer),ci=(di+bs.length)%4,side=ci%2;if(b==='P')return true;if(b!=='X'&&b!=='XX'){const last=[...bs].reverse().find(x=>!['P','X','XX'].includes(x));if(!last)return true;const a=bidInfo(last),c=bidInfo(b);return c.level>a.level||(c.level===a.level&&strains.indexOf(c.strain)>strains.indexOf(a.strain));}let i=-1;for(let n=bs.length-1;n>=0;n--){if(bs[n]!=='P'){i=n;break;}}if(i<0)return false;const action=bs[i],ls=((di+i)%4)%2;if(b==='X')return action!=='X'&&action!=='XX'&&ls!==side;if(b==='XX')return action==='X'&&ls!==side;return false;};"+
 "const grid=document.querySelector('.bidgrid');if(!grid)return;grid.innerHTML='';const cr=document.createElement('div');cr.className='callrow';const cg=document.createElement('div');cg.className='contractgrid';grid.append(cr,cg);function add(p,b,c){const x=document.createElement('button');x.dataset.bid=b;x.textContent=names[b];if(c)x.className=c;x.onclick=function(){if(x.disabled)return;data().bids.push(b);save();};p.appendChild(x);}add(cr,'P','pass');add(cr,'X','double');add(cr,'XX','redouble');for(let l=1;l<=7;l++){add(cg,l+'C','clubs');add(cg,l+'D','diamonds');add(cg,l+'H','hearts');add(cg,l+'S','spades');add(cg,l+'NT','notrump');}"+
 "function colourAuction(){document.querySelectorAll('#auction .bid').forEach((el,i)=>{const b=data().bids[i];el.style.color='';el.style.fontWeight='700';if(b&&b!=='P'&&b!=='X'&&b!=='XX'){const s=b.slice(1);el.style.color=(s==='D'||s==='H')?'#d32626':(s==='NT'?'#17324d':'#111');}else if(b==='P')el.style.color='#299447';else if(b==='X')el.style.color='#2878c7';else if(b==='XX')el.style.color='#cf3434';});}"+
 "window.updateFastButtons=function(){const done=auctionFinished();grid.querySelectorAll('[data-bid]').forEach(x=>x.disabled=done||!window.legalBid(x.dataset.bid));colourAuction();};const oldRender=render;render=function(){oldRender();window.updateFastButtons();};render();"+
 "})();";webView.evaluateJavascript(js,null);}
 public class AndroidFiles{@JavascriptInterface public void saveTextFile(final String f,final String m,final String c){runOnUiThread(()->{pendingFileName=sanitizeFileName(f);pendingMimeType=(m==null||m.trim().isEmpty())?"text/plain":m;pendingContent=c==null?"":c;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(pendingMimeType);i.putExtra(Intent.EXTRA_TITLE,pendingFileName);startActivityForResult(i,REQ_SAVE_FILE);});}@JavascriptInterface public void openJsonFile(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/json","text/json","text/plain","application/octet-stream"});startActivityForResult(i,REQ_OPEN_JSON);});}}
 private String sanitizeFileName(String n){String r=(n==null||n.trim().isEmpty())?"bridge-session.json":n.trim();return r.replaceAll("[\\\\/:*?\"<>|]","-");}
 @Override protected void onActivityResult(int rq,int rs,Intent d){super.onActivityResult(rq,rs,d);if(rs!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();if(rq==REQ_SAVE_FILE){try(OutputStream o=getContentResolver().openOutputStream(u,"wt")){if(o==null)throw new Exception();o.write(pendingContent.getBytes(StandardCharsets.UTF_8));o.flush();Toast.makeText(this,"Backup saved",Toast.LENGTH_LONG).show();webView.evaluateJavascript("window.androidFileSaved && window.androidFileSaved("+JSONObject.quote(pendingFileName)+");",null);}catch(Exception e){Toast.makeText(this,"Could not save file",Toast.LENGTH_LONG).show();}finally{pendingFileName=pendingMimeType=pendingContent=null;}}else if(rq==REQ_OPEN_JSON){try(InputStream in=getContentResolver().openInputStream(u);BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder q=new StringBuilder();String l;while((l=r.readLine())!=null)q.append(l).append('\n');webView.evaluateJavascript("window.receiveImportedJson && window.receiveImportedJson("+JSONObject.quote(q.toString())+");",null);}catch(Exception e){Toast.makeText(this,"Could not open backup",Toast.LENGTH_LONG).show();}}}
 @Override public void onBackPressed(){if(webView!=null&&webView.canGoBack())webView.goBack();else super.onBackPressed();}@Override protected void onDestroy(){if(webView!=null){webView.removeJavascriptInterface("AndroidFiles");webView.destroy();}super.onDestroy();}
}
