package nz.co.cpc.bridgeauctionrecorder;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.webkit.JavascriptInterface;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.pdf.PdfDocument;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
 private static final int REQ_SAVE_FILE=1001,REQ_OPEN_JSON=1002,REQ_SAVE_PDF=1003; private WebView webView; private String pendingFileName,pendingMimeType,pendingContent,pendingPdfJson;
 @Override protected void onCreate(Bundle b){super.onCreate(b);webView=new WebView(this);webView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE);setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setBuiltInZoomControls(false);s.setDisplayZoomControls(false);webView.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){super.onPageFinished(v,u);installCompactUi();}});webView.setWebChromeClient(new WebChromeClient());webView.addJavascriptInterface(new AndroidFiles(),"AndroidFiles");webView.loadUrl("file:///android_asset/www/index.html");}
 private void installCompactUi(){String js="(function(){"+
 "const st=document.createElement('style');st.textContent=`header{padding:7px 10px}h1{font-size:18px;margin:0 0 1px}.meta{font-size:11px}main{padding:4px 6px max(56px,calc(20px + env(safe-area-inset-bottom)))}.card{padding:6px;margin-bottom:4px;border-radius:9px}.grid{gap:5px}.section-title{margin-bottom:2px}.auction .seat,.auction .bid{padding:4px}.bid{min-height:31px}.last{outline:2px solid #a7bfd2}.bidgrid{display:block!important;margin-top:4px!important}.callrow{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;margin-bottom:4px}.contractgrid{display:grid;grid-template-columns:repeat(5,1fr);gap:3px}.bidgrid button{min-height:43px!important;padding:4px 2px!important;font-size:18px;border-radius:7px}.callrow button{font-size:17px;color:#fff}.callrow .pass{background:#299447;border-color:#237f3d}.callrow .double{background:#2878c7;border-color:#2169af}.callrow .redouble{background:#cf3434;border-color:#b82d2d}.callrow .undoCall{background:#f4f7fa;color:#17324d;border:2px solid #17324d}.contractgrid .clubs,.contractgrid .spades{color:#111}.contractgrid .diamonds,.contractgrid .hearts{color:#d32626}.contractgrid .notrump{color:#17324d}.bidgrid button:disabled{background:#d9dde0!important;color:#92989d!important;border-color:#c8cdd1!important;opacity:1}.tools{margin-top:4px}.liveControls{grid-template-columns:1fr 1fr!important}.liveControls label:first-child{display:none}.liveControls label:nth-child(4){display:none}.finalBidRow{display:none!important}#alertBtn,#alertBox{display:none!important}.sessionPrompt{display:flex;gap:5px;align-items:end;margin-bottom:4px}.sessionPrompt label{flex:1}.sessionPrompt input{margin-top:2px;padding:6px 8px}.sessionPrompt button{padding:6px 10px}.sessionPrompt.hidden{display:none}`;document.head.appendChild(st);"+
 "const top=document.querySelector('main .card .grid');if(top)top.classList.add('liveControls');"+
 "const firstCard=document.querySelector('main .card');const sp=document.createElement('div');sp.className='card sessionPrompt';sp.innerHTML=\"<label>Session name<input id='quickSessionName' placeholder='e.g. Monday Pairs 8 Sept'></label><button id='saveSessionName' class='primary'>Set</button>\";if(firstCard)firstCard.parentNode.insertBefore(sp,firstCard);const si=document.getElementById('quickSessionName');const sb=document.getElementById('saveSessionName');si.value=state.session||'';function finishSessionName(){const v=si.value.trim();if(!v)return;state.session=v;const original=document.getElementById('sessionName');if(original)original.value=v;localStorage.setItem(KEY,JSON.stringify(state));sp.classList.add('hidden');render();}sb.onclick=finishSessionName;si.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();finishSessionName();}};if(state.session)sp.classList.add('hidden');const meta=document.getElementById('sessionMeta');if(meta)meta.onclick=()=>{si.value=state.session||'';sp.classList.remove('hidden');si.focus();};"+
 "window.legalBid=function(b){const d=data(),bs=d.bids,di=seats.indexOf(d.dealer),ci=(di+bs.length)%4,side=ci%2;if(b==='P')return true;if(b!=='X'&&b!=='XX'){const last=[...bs].reverse().find(x=>!['P','X','XX'].includes(x));if(!last)return true;const a=bidInfo(last),c=bidInfo(b);return c.level>a.level||(c.level===a.level&&strains.indexOf(c.strain)>strains.indexOf(a.strain));}let i=-1;for(let n=bs.length-1;n>=0;n--){if(bs[n]!=='P'){i=n;break;}}if(i<0)return false;const action=bs[i],ls=((di+i)%4)%2;if(b==='X')return action!=='X'&&action!=='XX'&&ls!==side;if(b==='XX')return action==='X'&&ls!==side;return false;};"+
 "const grid=document.querySelector('.bidgrid');if(!grid)return;grid.innerHTML='';const cr=document.createElement('div');cr.className='callrow';const cg=document.createElement('div');cg.className='contractgrid';grid.append(cr,cg);function add(p,b,c){const x=document.createElement('button');x.dataset.bid=b;x.textContent=names[b];if(c)x.className=c;x.onclick=function(){if(x.disabled)return;data().bids.push(b);save();};p.appendChild(x);}add(cr,'P','pass');add(cr,'X','double');add(cr,'XX','redouble');const undo=document.getElementById('undo');if(undo){undo.className='undoCall';undo.textContent='↶ Undo';cr.appendChild(undo);}for(let l=1;l<=7;l++){add(cg,l+'C','clubs');add(cg,l+'D','diamonds');add(cg,l+'H','hearts');add(cg,l+'S','spades');add(cg,l+'NT','notrump');}"+
 "function colourAuction(){document.querySelectorAll('#auction .bid').forEach((el,i)=>{const b=data().bids[i];el.style.color='';el.style.fontWeight='700';if(b&&b!=='P'&&b!=='X'&&b!=='XX'){const s=b.slice(1);el.style.color=(s==='D'||s==='H')?'#d32626':(s==='NT'?'#17324d':'#111');}else if(b==='P')el.style.color='#299447';else if(b==='X')el.style.color='#2878c7';else if(b==='XX')el.style.color='#cf3434';});}"+
 "window.updateFastButtons=function(){const done=auctionFinished();grid.querySelectorAll('[data-bid]').forEach(x=>x.disabled=done||!window.legalBid(x.dataset.bid));colourAuction();};const oldRender=render;render=function(){oldRender();window.updateFastButtons();};"+
 "const ex=document.getElementById('exportJson');if(ex)ex.onclick=function(){const base=(state.session||'bridge-session').trim()||'bridge-session';const name=base.replace(/[\\\\/:*?\"<>|]/g,'-')+'.json';if(window.AndroidFiles&&AndroidFiles.saveTextFile)AndroidFiles.saveTextFile(name,'application/json',JSON.stringify(state,null,2));};"+
 "const printBtn=document.getElementById('print');if(printBtn){printBtn.textContent='Save Summary PDF';printBtn.onclick=function(){if(window.AndroidFiles&&AndroidFiles.saveSummaryPdf)AndroidFiles.saveSummaryPdf(JSON.stringify(state));};}"+
 "const pbn=document.getElementById('exportPbn'),restore=document.getElementById('importBtn'),newBtn=document.getElementById('newSession');if(pbn&&restore){pbn.replaceWith(restore);}if(newBtn){newBtn.textContent='End Session';newBtn.onclick=function(){const count=Object.keys(state.boards).filter(n=>state.boards[n].bids&&state.boards[n].bids.length).length;const msg='End '+(state.session||'this session')+'?\\n\\nThis clears the working session from the app so you can start a new one.'+(count?' Make sure you have saved the JSON backup first.':'');if(!confirm(msg))return;state={version:2,session:'',current:1,boards:{}};localStorage.setItem(KEY,JSON.stringify(state));si.value='';sp.classList.remove('hidden');render();scrollTo(0,0);setTimeout(()=>si.focus(),100);};}"+
 "render();})();";webView.evaluateJavascript(js,null);}
 public class AndroidFiles{
  @JavascriptInterface public void saveTextFile(final String f,final String m,final String c){runOnUiThread(()->{pendingFileName=sanitizeFileName(f);pendingMimeType=(m==null||m.trim().isEmpty())?"text/plain":m;pendingContent=c==null?"":c;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(pendingMimeType);i.putExtra(Intent.EXTRA_TITLE,pendingFileName);startActivityForResult(i,REQ_SAVE_FILE);});}
  @JavascriptInterface public void openJsonFile(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/json","text/json","text/plain","application/octet-stream"});startActivityForResult(i,REQ_OPEN_JSON);});}
  @JavascriptInterface public void saveSummaryPdf(final String json){runOnUiThread(()->{try{JSONObject root=new JSONObject(json);String base=root.optString("session","bridge-session").trim();if(base.isEmpty())base="bridge-session";pendingFileName=sanitizeFileName(base+" Summary.pdf");pendingPdfJson=json;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,pendingFileName);startActivityForResult(i,REQ_SAVE_PDF);}catch(Exception e){Toast.makeText(MainActivity.this,"Could not prepare summary",Toast.LENGTH_LONG).show();}});}
 }
 private String sanitizeFileName(String n){String r=(n==null||n.trim().isEmpty())?"bridge-session.json":n.trim();return r.replaceAll("[\\\\/:*?\"<>|]","-");}
 private String callName(String b){if("P".equals(b))return "Pass";if("X".equals(b))return "X";if("XX".equals(b))return "XX";if(b.endsWith("C"))return b.substring(0,b.length()-1)+"♣";if(b.endsWith("D"))return b.substring(0,b.length()-1)+"♦";if(b.endsWith("H"))return b.substring(0,b.length()-1)+"♥";if(b.endsWith("S"))return b.substring(0,b.length()-1)+"♠";return b;}
 private int seatIndex(String s){if("East".equals(s))return 1;if("South".equals(s))return 2;if("West".equals(s))return 3;return 0;}
 private void writeSummaryPdf(Uri uri)throws Exception{
  JSONObject root=new JSONObject(pendingPdfJson);JSONObject boards=root.optJSONObject("boards");PdfDocument pdf=new PdfDocument();Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));int pageNo=0,y=0;PdfDocument.Page page=null;Canvas c=null;
  for(int n=1;n<=36;n++){JSONObject b=boards==null?null:boards.optJSONObject(String.valueOf(n));JSONArray bids=b==null?null:b.optJSONArray("bids");if(bids==null||bids.length()==0)continue;int rows=(bids.length()+3)/4;int need=70+rows*22;if(page==null||y+need>790){if(page!=null)pdf.finishPage(page);pageNo++;page=pdf.startPage(new PdfDocument.PageInfo.Builder(595,842,pageNo).create());c=page.getCanvas();y=48;p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(20);c.drawText("Bridge Auction Recorder",40,y,p);y+=24;p.setTextSize(13);c.drawText(root.optString("session","Untitled session"),40,y,p);y+=30;}
   p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(14);c.drawText("Board "+n,40,y,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(11);c.drawText("Dealer: "+b.optString("dealer","North")+"    Vulnerability: "+b.optString("vul","None"),115,y,p);y+=20;
   String[] seats={"North","East","South","West"};int di=seatIndex(b.optString("dealer","North"));float[] xs={55,180,305,430};p.setTypeface(Typeface.DEFAULT_BOLD);for(int col=0;col<4;col++)c.drawText(seats[(di+col)%4],xs[col],y,p);y+=18;p.setTypeface(Typeface.DEFAULT);p.setTextSize(12);
   for(int i=0;i<bids.length();i+=4){for(int col=0;col<4&&i+col<bids.length();col++)c.drawText(callName(bids.optString(i+col)),xs[col],y,p);y+=22;}y+=14;
  }
  if(page==null){page=pdf.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());c=page.getCanvas();p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(20);c.drawText("Bridge Auction Recorder",40,50,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(13);c.drawText("No boards recorded.",40,85,p);}pdf.finishPage(page);try(OutputStream o=getContentResolver().openOutputStream(uri,"wt")){if(o==null)throw new Exception();pdf.writeTo(o);}finally{pdf.close();}
 }
 @Override protected void onActivityResult(int rq,int rs,Intent d){super.onActivityResult(rq,rs,d);if(rs!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();if(rq==REQ_SAVE_FILE){try(OutputStream o=getContentResolver().openOutputStream(u,"wt")){if(o==null)throw new Exception();o.write(pendingContent.getBytes(StandardCharsets.UTF_8));o.flush();Toast.makeText(this,"Backup saved",Toast.LENGTH_LONG).show();webView.evaluateJavascript("window.androidFileSaved && window.androidFileSaved("+JSONObject.quote(pendingFileName)+");",null);}catch(Exception e){Toast.makeText(this,"Could not save file",Toast.LENGTH_LONG).show();}finally{pendingFileName=pendingMimeType=pendingContent=null;}}else if(rq==REQ_SAVE_PDF){try{writeSummaryPdf(u);Toast.makeText(this,"Summary PDF saved",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Could not save summary PDF",Toast.LENGTH_LONG).show();}finally{pendingPdfJson=null;pendingFileName=null;}}else if(rq==REQ_OPEN_JSON){try(InputStream in=getContentResolver().openInputStream(u);BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder q=new StringBuilder();String l;while((l=r.readLine())!=null)q.append(l).append('\n');webView.evaluateJavascript("window.receiveImportedJson && window.receiveImportedJson("+JSONObject.quote(q.toString())+");",null);}catch(Exception e){Toast.makeText(this,"Could not open backup",Toast.LENGTH_LONG).show();}}}
 @Override public void onBackPressed(){if(webView!=null&&webView.canGoBack())webView.goBack();else super.onBackPressed();}@Override protected void onDestroy(){if(webView!=null){webView.removeJavascriptInterface("AndroidFiles");webView.destroy();}super.onDestroy();}
}
